<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <?php
    include_once(__DIR__ . "/../../config/config/config.php")
    ?>

    <link rel="stylesheet" href="<?php echo constant('HOST') ?>/assets/css/home.css">

    <link rel="stylesheet" href="<?php echo constant('HOST') ?>/assets/css/vendors/all.min.css">
</head>

<body>
    <?php
    include_once(__DIR__ . "/../../components/nav.php")
    ?>

    <div class="w-full">
        <img class="w-full h-[80vh]" src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
    </div>

    <section id="about-us" class="section-contain flex gap-2 py-10">
        <img class="scroll-animation-item-multimedia" src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <div class="scroll-animation-item-contain ">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti debitis aliquid deserunt eaque atque dignissimos nulla facere soluta ut sunt quia voluptas adipisci dolore deleniti architecto voluptates, numquam vel error quos modi, nobis quae ipsam praesentium amet! Excepturi nemo veritatis dolorem repellat eius, maxime officiis vel quos architecto quisquam nostrum sed pariatur fugiat voluptas deserunt autem iste culpa temporibus! Natus ducimus, cum expedita odio fuga repudiandae maiores, harum minima, qui nihil voluptatum mollitia quibusdam totam! Dolor harum architecto officia aliquid adipisci provident voluptas accusamus sint maxime consequuntur, beatae porro quas iusto temporibus ipsum quisquam corrupti saepe id corporis. Voluptatum nemo tempore optio modi, illo aliquid libero incidunt dolor sed nesciunt minima rerum veniam alias, voluptate dolorum! Iusto maxime, error voluptates quis eveniet cumque sunt distinctio nostrum tenetur ad ipsam. Doloribus iure, totam ab blanditiis sequi ipsum labore, eligendi velit, doloremque voluptate quod tempore quidem dolore commodi? Mollitia, accusamus neque. Iusto explicabo voluptates illum sunt voluptatem deleniti? Qui aut temporibus, sit possimus voluptas adipisci mollitia assumenda ipsa commodi enim. Quo amet autem repudiandae odit, aliquam eligendi cupiditate. Quo, eligendi maxime nam vero, non quidem suscipit magnam dolorum aut similique ea odio voluptatibus animi autem perspiciatis beatae ipsam? Soluta in assumenda excepturi provident alias nulla praesentium explicabo corrupti, sint doloribus delectus debitis recusandae distinctio laudantium. Officiis totam iusto nihil eveniet veritatis quo maxime pariatur esse veniam ipsam? Quos ipsa sequi accusantium ducimus minus dolorem iure ab aperiam illum asperiores modi exercitationem incidunt nesciunt adipisci placeat, esse corrupti debitis assumenda consequatur laborum. Voluptas architecto quisquam quae sint at voluptates voluptatem a incidunt fugiat quibusdam nihil assumenda, doloremque perspiciatis cum iste harum nisi omnis cupiditate fuga maiores porro accusantium natus modi. Perspiciatis maiores in mollitia nesciunt delectus, laborum, tempora voluptatibus quia sapiente sit ipsa. Ab aperiam obcaecati odio perspiciatis, enim ex quod minus laudantium!
        </div>
    </section>
    <section class="section-contain scroll-animation-item">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla ipsum recusandae voluptate suscipit fuga neque tenetur voluptas, ut voluptatum voluptates aspernatur ipsa eaque, soluta et repudiandae fugit minus! Molestiae, quo quidem quibusdam, quae quas voluptates atque officiis ullam dolorem assumenda ad tempore facilis cumque, exercitationem illo? Illum consectetur doloremque veritatis nobis voluptatum obcaecati suscipit ipsam recusandae pariatur, nihil nulla cupiditate similique fugit nostrum, aliquam facere repudiandae a aspernatur placeat dolore eaque quas voluptatem rem? Dolores enim nobis, dicta exercitationem odio illum, repellendus in fuga sapiente eos deserunt illo, harum ab iure? Est cupiditate omnis libero vitae alias. Esse ipsa assumenda, aspernatur temporibus natus quidem iure voluptatem maiores eaque labore nihil at explicabo alias repellendus qui hic aliquam consectetur quibusdam? Nesciunt ducimus nisi vero esse quisquam dignissimos impedit quia, quam debitis veniam aperiam ad dolores eum adipisci necessitatibus facere cum, commodi totam itaque. Possimus, quod rerum! Cum voluptas ipsum possimus officia expedita hic praesentium veniam odio temporibus nostrum inventore vitae, exercitationem tempora quo impedit sed minus dicta perferendis eligendi minima, nam eveniet aliquam veritatis reprehenderit! Asperiores nemo voluptatum, suscipit, odio temporibus accusamus dolorum necessitatibus voluptatem quis in vel esse id fugiat? Fuga illo est quaerat impedit aspernatur reiciendis soluta harum temporibus itaque beatae non voluptatibus rerum veniam consequuntur odio perspiciatis libero optio dolorem, cupiditate ex nostrum hic nemo! Consequatur debitis nemo quod quis modi repellat nulla numquam, officia vero iste eligendi nihil quia ipsa expedita quaerat nam repudiandae distinctio ut, consectetur veniam quisquam. Voluptatibus laudantium, mollitia explicabo optio possimus, adipisci modi, soluta neque harum amet debitis! Tempora facilis nisi veritatis rerum quaerat laudantium modi. Odio quibusdam ullam voluptate molestiae ratione pariatur ad illo! Quod vitae deleniti nobis. Perspiciatis vel possimus ipsum natus veniam sunt? Id a cumque consequuntur aperiam nam eligendi non voluptatibus atque cupiditate nemo deserunt, cum distinctio ipsam. Veritatis.</section>
    <section class="section-contain scroll-animation-item">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla ipsum recusandae voluptate suscipit fuga neque tenetur voluptas, ut voluptatum voluptates aspernatur ipsa eaque, soluta et repudiandae fugit minus! Molestiae, quo quidem quibusdam, quae quas voluptates atque officiis ullam dolorem assumenda ad tempore facilis cumque, exercitationem illo? Illum consectetur doloremque veritatis nobis voluptatum obcaecati suscipit ipsam recusandae pariatur, nihil nulla cupiditate similique fugit nostrum, aliquam facere repudiandae a aspernatur placeat dolore eaque quas voluptatem rem? Dolores enim nobis, dicta exercitationem odio illum, repellendus in fuga sapiente eos deserunt illo, harum ab iure? Est cupiditate omnis libero vitae alias. Esse ipsa assumenda, aspernatur temporibus natus quidem iure voluptatem maiores eaque labore nihil at explicabo alias repellendus qui hic aliquam consectetur quibusdam? Nesciunt ducimus nisi vero esse quisquam dignissimos impedit quia, quam debitis veniam aperiam ad dolores eum adipisci necessitatibus facere cum, commodi totam itaque. Possimus, quod rerum! Cum voluptas ipsum possimus officia expedita hic praesentium veniam odio temporibus nostrum inventore vitae, exercitationem tempora quo impedit sed minus dicta perferendis eligendi minima, nam eveniet aliquam veritatis reprehenderit! Asperiores nemo voluptatum, suscipit, odio temporibus accusamus dolorum necessitatibus voluptatem quis in vel esse id fugiat? Fuga illo est quaerat impedit aspernatur reiciendis soluta harum temporibus itaque beatae non voluptatibus rerum veniam consequuntur odio perspiciatis libero optio dolorem, cupiditate ex nostrum hic nemo! Consequatur debitis nemo quod quis modi repellat nulla numquam, officia vero iste eligendi nihil quia ipsa expedita quaerat nam repudiandae distinctio ut, consectetur veniam quisquam. Voluptatibus laudantium, mollitia explicabo optio possimus, adipisci modi, soluta neque harum amet debitis! Tempora facilis nisi veritatis rerum quaerat laudantium modi. Odio quibusdam ullam voluptate molestiae ratione pariatur ad illo! Quod vitae deleniti nobis. Perspiciatis vel possimus ipsum natus veniam sunt? Id a cumque consequuntur aperiam nam eligendi non voluptatibus atque cupiditate nemo deserunt, cum distinctio ipsam. Veritatis.</section>
    <section id="benefits" class="section-contain scroll-animation-item flex gap-2 py-10">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <div class="scroll-animation-item">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti debitis aliquid deserunt eaque atque dignissimos nulla facere soluta ut sunt quia voluptas adipisci dolore deleniti architecto voluptates, numquam vel error quos modi, nobis quae ipsam praesentium amet! Excepturi nemo veritatis dolorem repellat eius, maxime officiis vel quos architecto quisquam nostrum sed pariatur fugiat voluptas deserunt autem iste culpa temporibus! Natus ducimus, cum expedita odio fuga repudiandae maiores, harum minima, qui nihil voluptatum mollitia quibusdam totam! Dolor harum architecto officia aliquid adipisci provident voluptas accusamus sint maxime consequuntur, beatae porro quas iusto temporibus ipsum quisquam corrupti saepe id corporis. Voluptatum nemo tempore optio modi, illo aliquid libero incidunt dolor sed nesciunt minima rerum veniam alias, voluptate dolorum! Iusto maxime, error voluptates quis eveniet cumque sunt distinctio nostrum tenetur ad ipsam. Doloribus iure, totam ab blanditiis sequi ipsum labore, eligendi velit, doloremque voluptate quod tempore quidem dolore commodi? Mollitia, accusamus neque. Iusto explicabo voluptates illum sunt voluptatem deleniti? Qui aut temporibus, sit possimus voluptas adipisci mollitia assumenda ipsa commodi enim. Quo amet autem repudiandae odit, aliquam eligendi cupiditate. Quo, eligendi maxime nam vero, non quidem suscipit magnam dolorum aut similique ea odio voluptatibus animi autem perspiciatis beatae ipsam? Soluta in assumenda excepturi provident alias nulla praesentium explicabo corrupti, sint doloribus delectus debitis recusandae distinctio laudantium. Officiis totam iusto nihil eveniet veritatis quo maxime pariatur esse veniam ipsam? Quos ipsa sequi accusantium ducimus minus dolorem iure ab aperiam illum asperiores modi exercitationem incidunt nesciunt adipisci placeat, esse corrupti debitis assumenda consequatur laborum. Voluptas architecto quisquam quae sint at voluptates voluptatem a incidunt fugiat quibusdam nihil assumenda, doloremque perspiciatis cum iste harum nisi omnis cupiditate fuga maiores porro accusantium natus modi. Perspiciatis maiores in mollitia nesciunt delectus, laborum, tempora voluptatibus quia sapiente sit ipsa. Ab aperiam obcaecati odio perspiciatis, enim ex quod minus laudantium!
        </div>
    </section>
    <section class="section-contain scroll-animation-item">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla ipsum recusandae voluptate suscipit fuga neque tenetur voluptas, ut voluptatum voluptates aspernatur ipsa eaque, soluta et repudiandae fugit minus! Molestiae, quo quidem quibusdam, quae quas voluptates atque officiis ullam dolorem assumenda ad tempore facilis cumque, exercitationem illo? Illum consectetur doloremque veritatis nobis voluptatum obcaecati suscipit ipsam recusandae pariatur, nihil nulla cupiditate similique fugit nostrum, aliquam facere repudiandae a aspernatur placeat dolore eaque quas voluptatem rem? Dolores enim nobis, dicta exercitationem odio illum, repellendus in fuga sapiente eos deserunt illo, harum ab iure? Est cupiditate omnis libero vitae alias. Esse ipsa assumenda, aspernatur temporibus natus quidem iure voluptatem maiores eaque labore nihil at explicabo alias repellendus qui hic aliquam consectetur quibusdam? Nesciunt ducimus nisi vero esse quisquam dignissimos impedit quia, quam debitis veniam aperiam ad dolores eum adipisci necessitatibus facere cum, commodi totam itaque. Possimus, quod rerum! Cum voluptas ipsum possimus officia expedita hic praesentium veniam odio temporibus nostrum inventore vitae, exercitationem tempora quo impedit sed minus dicta perferendis eligendi minima, nam eveniet aliquam veritatis reprehenderit! Asperiores nemo voluptatum, suscipit, odio temporibus accusamus dolorum necessitatibus voluptatem quis in vel esse id fugiat? Fuga illo est quaerat impedit aspernatur reiciendis soluta harum temporibus itaque beatae non voluptatibus rerum veniam consequuntur odio perspiciatis libero optio dolorem, cupiditate ex nostrum hic nemo! Consequatur debitis nemo quod quis modi repellat nulla numquam, officia vero iste eligendi nihil quia ipsa expedita quaerat nam repudiandae distinctio ut, consectetur veniam quisquam. Voluptatibus laudantium, mollitia explicabo optio possimus, adipisci modi, soluta neque harum amet debitis! Tempora facilis nisi veritatis rerum quaerat laudantium modi. Odio quibusdam ullam voluptate molestiae ratione pariatur ad illo! Quod vitae deleniti nobis. Perspiciatis vel possimus ipsum natus veniam sunt? Id a cumque consequuntur aperiam nam eligendi non voluptatibus atque cupiditate nemo deserunt, cum distinctio ipsam. Veritatis.</section>
    <section id="courses" class="section-contain scroll-animation-item">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla ipsum recusandae voluptate suscipit fuga neque tenetur voluptas, ut voluptatum voluptates aspernatur ipsa eaque, soluta et repudiandae fugit minus! Molestiae, quo quidem quibusdam, quae quas voluptates atque officiis ullam dolorem assumenda ad tempore facilis cumque, exercitationem illo? Illum consectetur doloremque veritatis nobis voluptatum obcaecati suscipit ipsam recusandae pariatur, nihil nulla cupiditate similique fugit nostrum, aliquam facere repudiandae a aspernatur placeat dolore eaque quas voluptatem rem? Dolores enim nobis, dicta exercitationem odio illum, repellendus in fuga sapiente eos deserunt illo, harum ab iure? Est cupiditate omnis libero vitae alias. Esse ipsa assumenda, aspernatur temporibus natus quidem iure voluptatem maiores eaque labore nihil at explicabo alias repellendus qui hic aliquam consectetur quibusdam? Nesciunt ducimus nisi vero esse quisquam dignissimos impedit quia, quam debitis veniam aperiam ad dolores eum adipisci necessitatibus facere cum, commodi totam itaque. Possimus, quod rerum! Cum voluptas ipsum possimus officia expedita hic praesentium veniam odio temporibus nostrum inventore vitae, exercitationem tempora quo impedit sed minus dicta perferendis eligendi minima, nam eveniet aliquam veritatis reprehenderit! Asperiores nemo voluptatum, suscipit, odio temporibus accusamus dolorum necessitatibus voluptatem quis in vel esse id fugiat? Fuga illo est quaerat impedit aspernatur reiciendis soluta harum temporibus itaque beatae non voluptatibus rerum veniam consequuntur odio perspiciatis libero optio dolorem, cupiditate ex nostrum hic nemo! Consequatur debitis nemo quod quis modi repellat nulla numquam, officia vero iste eligendi nihil quia ipsa expedita quaerat nam repudiandae distinctio ut, consectetur veniam quisquam. Voluptatibus laudantium, mollitia explicabo optio possimus, adipisci modi, soluta neque harum amet debitis! Tempora facilis nisi veritatis rerum quaerat laudantium modi. Odio quibusdam ullam voluptate molestiae ratione pariatur ad illo! Quod vitae deleniti nobis. Perspiciatis vel possimus ipsum natus veniam sunt? Id a cumque consequuntur aperiam nam eligendi non voluptatibus atque cupiditate nemo deserunt, cum distinctio ipsam. Veritatis.</section>
    <section class="section-contain scroll-animation-item">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla ipsum recusandae voluptate suscipit fuga neque tenetur voluptas, ut voluptatum voluptates aspernatur ipsa eaque, soluta et repudiandae fugit minus! Molestiae, quo quidem quibusdam, quae quas voluptates atque officiis ullam dolorem assumenda ad tempore facilis cumque, exercitationem illo? Illum consectetur doloremque veritatis nobis voluptatum obcaecati suscipit ipsam recusandae pariatur, nihil nulla cupiditate similique fugit nostrum, aliquam facere repudiandae a aspernatur placeat dolore eaque quas voluptatem rem? Dolores enim nobis, dicta exercitationem odio illum, repellendus in fuga sapiente eos deserunt illo, harum ab iure? Est cupiditate omnis libero vitae alias. Esse ipsa assumenda, aspernatur temporibus natus quidem iure voluptatem maiores eaque labore nihil at explicabo alias repellendus qui hic aliquam consectetur quibusdam? Nesciunt ducimus nisi vero esse quisquam dignissimos impedit quia, quam debitis veniam aperiam ad dolores eum adipisci necessitatibus facere cum, commodi totam itaque. Possimus, quod rerum! Cum voluptas ipsum possimus officia expedita hic praesentium veniam odio temporibus nostrum inventore vitae, exercitationem tempora quo impedit sed minus dicta perferendis eligendi minima, nam eveniet aliquam veritatis reprehenderit! Asperiores nemo voluptatum, suscipit, odio temporibus accusamus dolorum necessitatibus voluptatem quis in vel esse id fugiat? Fuga illo est quaerat impedit aspernatur reiciendis soluta harum temporibus itaque beatae non voluptatibus rerum veniam consequuntur odio perspiciatis libero optio dolorem, cupiditate ex nostrum hic nemo! Consequatur debitis nemo quod quis modi repellat nulla numquam, officia vero iste eligendi nihil quia ipsa expedita quaerat nam repudiandae distinctio ut, consectetur veniam quisquam. Voluptatibus laudantium, mollitia explicabo optio possimus, adipisci modi, soluta neque harum amet debitis! Tempora facilis nisi veritatis rerum quaerat laudantium modi. Odio quibusdam ullam voluptate molestiae ratione pariatur ad illo! Quod vitae deleniti nobis. Perspiciatis vel possimus ipsum natus veniam sunt? Id a cumque consequuntur aperiam nam eligendi non voluptatibus atque cupiditate nemo deserunt, cum distinctio ipsam. Veritatis.</section>
    <section id="customers" class="section-images">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">

        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">

        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
    </section>
    <section class="section-contain scroll-animation-item flex gap-2 py-10">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <div class="scroll-animation-item">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti debitis aliquid deserunt eaque atque dignissimos nulla facere soluta ut sunt quia voluptas adipisci dolore deleniti architecto voluptates, numquam vel error quos modi, nobis quae ipsam praesentium amet! Excepturi nemo veritatis dolorem repellat eius, maxime officiis vel quos architecto quisquam nostrum sed pariatur fugiat voluptas deserunt autem iste culpa temporibus! Natus ducimus, cum expedita odio fuga repudiandae maiores, harum minima, qui nihil voluptatum mollitia quibusdam totam! Dolor harum architecto officia aliquid adipisci provident voluptas accusamus sint maxime consequuntur, beatae porro quas iusto temporibus ipsum quisquam corrupti saepe id corporis. Voluptatum nemo tempore optio modi, illo aliquid libero incidunt dolor sed nesciunt minima rerum veniam alias, voluptate dolorum! Iusto maxime, error voluptates quis eveniet cumque sunt distinctio nostrum tenetur ad ipsam. Doloribus iure, totam ab blanditiis sequi ipsum labore, eligendi velit, doloremque voluptate quod tempore quidem dolore commodi? Mollitia, accusamus neque. Iusto explicabo voluptates illum sunt voluptatem deleniti? Qui aut temporibus, sit possimus voluptas adipisci mollitia assumenda ipsa commodi enim. Quo amet autem repudiandae odit, aliquam eligendi cupiditate. Quo, eligendi maxime nam vero, non quidem suscipit magnam dolorum aut similique ea odio voluptatibus animi autem perspiciatis beatae ipsam? Soluta in assumenda excepturi provident alias nulla praesentium explicabo corrupti, sint doloribus delectus debitis recusandae distinctio laudantium. Officiis totam iusto nihil eveniet veritatis quo maxime pariatur esse veniam ipsam? Quos ipsa sequi accusantium ducimus minus dolorem iure ab aperiam illum asperiores modi exercitationem incidunt nesciunt adipisci placeat, esse corrupti debitis assumenda consequatur laborum. Voluptas architecto quisquam quae sint at voluptates voluptatem a incidunt fugiat quibusdam nihil assumenda, doloremque perspiciatis cum iste harum nisi omnis cupiditate fuga maiores porro accusantium natus modi. Perspiciatis maiores in mollitia nesciunt delectus, laborum, tempora voluptatibus quia sapiente sit ipsa. Ab aperiam obcaecati odio perspiciatis, enim ex quod minus laudantium!
        </div>
    </section>
    <section class="section-images">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">

        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">

        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
        <img src="<?php echo constant("HOST") ?>/public/img/future.jpg" alt="img">
    </section>


    <script src="https://kit.fontawesome.com/760e3cbc52.js" crossorigin="anonymous"></script>
    <script src="/assets/js/header.js"></script>
    <script src="<?php echo constant("HOST") ?>/assets/js/header.js"></script>
</body>

</html>